<?php
/**
 * @file
 *
 *
 *
 *
 */

// Load fedora_item.inc from the fedora_repository module in the api folder.
module_load_include('inc', 'fedora_repository', 'api/fedora_item');

/**
 * Implementation of hook_help().
 */
function islandora_upload_help($path, $arg) {
  switch ($path) {
    case 'admin/help#islandora_upload':
      $output = '<p>'. t('Islandora Upload Module') .'</p>';
      return $output;
    case 'admin/settings/uploads':
      return '<p>'. t('Users with the <a href="@permissions">attach files permission</a> can upload attachments. Users with the <a href="@permissions">view attached files permission</a> can view uploaded attachments. You can choose which post types can take attachments on the <a href="@types">content types settings</a> page.', array('@permissions' => url('admin/user/permissions', array('fragment' => 'module-islandora_upload')), '@types' => url('admin/content/types'))) .'</p>';
  }
}

/**
 * Implementation of hook_theme().
 */
function islandora_upload_theme() {
  return array(
    'islandora_upload_attachments' => array(
      'arguments' => array('islandora_files' => NULL),
    ),
    'islandora_upload_form_current' => array(
      'arguments' => array('form' => NULL),
    ),
    'islandora_upload_form_new' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

/**
 * Implementation of hook_link().
 */
function islandora_upload_link($type, $node = NULL, $teaser = FALSE) {
  $links = array();

  // Display a link with the number of attachments
  if ($teaser && $type == 'node' && isset($node->islandora_files) && user_access('view attached files')) {
    $num_files = 0;
    foreach ($node->islandora_files as $file) {
      if ($file->list) {
        $num_files++;
      }
    }
    if ($num_files) {
      $links['islandora_upload_attachments'] = array(
        'title' => format_plural($num_files, '1 attachment', '@count attachments'),
        'href' => "node/$node->nid",
        'attributes' => array('title' => t('Read full article to view attachments.')),
        'fragment' => 'attachments'
      );
    }
  }

  return $links;
}

/**
 * Implementation of hook_perm().
 */
function islandora_upload_perm() {
  return array('attach files', 'view attached files');
}

/**
 * Implementation of hook_menu().
 */
function islandora_upload_menu() {
  $items = array();

  $items['islandora_upload/js'] = array(
    'page callback' => 'islandora_upload_js',
    'access arguments' => array('attach files'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/islandorauploads'] = array(
    'title' => 'Islandora Upload',
    'description' => 'Control how files may be attached to content.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_upload_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'islandora_upload.admin.inc',
  );
  $items['node/islandora_file_permissions'] = array(
    'title' => t('Set File Access Permissions'),
    'page callback' => 'islandora_upload_permissions_form',
    'description' => t('Set File Access Permissions'),
    'access arguments' => array('attach files'),
    'type' => MENU_CALLBACK,
  );
  $items['filepermissions/get'] = array(
    'title' => 'Permissions',
    'page callback' => 'islandora_upload_get_by_file_id',
    'access arguments' => array('attach files'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

function islandora_upload_menu_alter(&$items) {
  $items['system/files']['access arguments'] = array('view attached files');
}

/**
 * Theme the attachments list.
 *
 * @ingroup themeable
 */
function theme_islandora_upload_form_current($form) {
  $header = array(t(''), t('Delete'), t('Description'), t('Weight'), t('Mime Type'), t('Size'));
  drupal_add_tabledrag('upload-attachments', 'order', 'sibling', 'upload-weight');

  foreach (element_children($form) as $key) {
    // Add class to group weight fields for drag and drop.
    $form[$key]['weight']['#attributes']['class'] = 'upload-weight';

    $row = array('');
    $row[] = drupal_render($form[$key]['remove']);
    //$row[] = drupal_render($form[$key]['list']);
    $row[] = drupal_render($form[$key]['description']);
    $row[] = drupal_render($form[$key]['weight']);
    $row[] = drupal_render($form[$key]['mimetype']);
    $row[] = drupal_render($form[$key]['size']);
    $rows[] = array('data' => $row, 'class' => 'draggable');
  }
  $output = theme('table', $header, $rows, array('id' => 'upload-attachments'));
  $output .= drupal_render($form);
  return $output;
}

/**
 * Theme the attachment form.
 * Note: required to output prefix/suffix.
 *
 * @ingroup themeable
 */
function theme_islandora_upload_form_new($form) {
  drupal_add_tabledrag('upload-attachments', 'order', 'sibling', 'upload-weight');
  $output = drupal_render($form);
  return $output;
}

/**
 * Determine the limitations on files that a given user may upload. The user
 * may be in multiple roles so we select the most permissive limitations from
 * all of their roles.
 *
 * @param $user
 *   A Drupal user object.
 * @return
 *   An associative array with the following keys:
 *     'extensions'
 *       A white space separated string containing all the file extensions this
 *       user may upload.
 *     'file_size'
 *       The maximum size of a file upload in bytes.
 *     'user_size'
 *       The total number of bytes for all for a user's files.
 *     'resolution'
 *       A string specifying the maximum resolution of images.
 */
function _islandora_upload_file_limits($user) {
  $file_limit = variable_get('upload_uploadsize_default', 1);
  $user_limit = variable_get('upload_usersize_default', 1);
  $all_extensions = explode(' ', variable_get('upload_extensions_default', 'jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp'));
  foreach ($user->roles as $rid => $name) {
    $extensions = variable_get("upload_extensions_$rid", variable_get('upload_extensions_default', 'jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp'));
    $all_extensions = array_merge($all_extensions, explode(' ', $extensions));

    // A zero value indicates no limit, take the least restrictive limit.
    $file_size = variable_get("upload_uploadsize_$rid", variable_get('upload_uploadsize_default', 1)) * 1024 * 1024;
    $file_limit = ($file_limit && $file_size) ? max($file_limit, $file_size) : 0;

    $user_size = variable_get("upload_usersize_$rid", variable_get('upload_usersize_default', 1)) * 1024 * 1024;
    $user_limit = ($user_limit && $user_size) ? max($user_limit, $user_size) : 0;
  }
  $all_extensions = implode(' ', array_unique($all_extensions));
  return array(
    'extensions' => $all_extensions,
    'file_size' => $file_limit,
    'user_size' => $user_limit,
    'resolution' => variable_get('upload_max_resolution', 0),
  );
}
/**
 * Check if the current user has access to the objects if so return true otherwise return false.
 *
 * @param $pid
 *   The object trying to be accessed.
 * @param $uid
 *   The user who is trying to access pid.
 */
function islandora_upload_check_object_access($pid, $uid) {
  return TRUE;
}

/**
 * Save new uploads and store them in the session to be associated to the node
 * on islandora_upload_save.
 *
 * @param $node
 *   A node object to associate with uploaded files.
 */
function islandora_upload_node_form_submit(&$form, &$form_state) {
  global $user;

  $limits = _islandora_upload_file_limits($user);
  $validators = array(
    'file_validate_extensions' => array($limits['extensions']),
    'file_validate_image_resolution' => array($limits['resolution']),
    'file_validate_size' => array($limits['file_size'], $limits['user_size']),
  );

  if (user_access('attach files'))  {
    $file = file_save_upload('upload', $validators, file_directory_path());
    $check = islandora_check_mime($file);
    if (!empty($check)) {
      drupal_set_message("$check", 'error');
      file_delete($file->filepath);
    }
    else {
      if (!empty($file)) {
        // Save new file uploads.
        $file->list = variable_get('upload_list_default', 1);
        $file->description = $file->filename;
        $file->weight = 0;
        $file->new = TRUE;
        $form['#node']->islandora_files[$file->fid] = $file;
        $form_state['values']['islandora_files'][$file->fid] = (array)$file;
      }
    }
    if (isset($form_state['values']['islandora_files'])) {
      foreach ($form_state['values']['islandora_files'] as $fid => $file) {
        // If the node was previewed prior to saving, $form['#node']->files[$fid]
        // is an array instead of an object. Convert file to object for compatibility.
        $form['#node']->islandora_files[$fid] = (object) $form['#node']->islandora_files[$fid];
        $form_state['values']['islandora_files'][$fid]['new'] = !empty($form['#node']->islandora_files[$fid]->new);
      }
    }

    // Order the form according to the set file weight values.
    if (!empty($form_state['values']['islandora_files'])) {
      $microweight = 0.001;
      foreach ($form_state['values']['islandora_files'] as $fid => $file) {
        if (is_numeric($fid)) {
          $form_state['values']['islandora_files'][$fid]['#weight'] = $file['weight'] + $microweight;
          $microweight += 0.001;
        }
      }
      uasort($form_state['values']['islandora_files'], 'element_sort');
    }

  }
}

/**
 *  Convert a fedora object into a file object so the form can display it like a file.
 *  @param $PID
 *  The PID to be converted into a file object.
 *  @return $file
 *  Returns the converted file or null and a drupal set message displaying an error that 'OBJ' datastream doesn't exist.
 */
function islandora_obj_to_file($PID) {

  module_load_include('inc', 'fedora_repository', 'api/fedora_item');

  $fedora_item = new Fedora_Item($PID);
  $path = $fedora_item->get_datastreams_list_as_array();

  if (array_key_exists('OBJ', $path)) {
    $label = $path['OBJ']['label'];
    $path = $path['OBJ']['URL'];
    preg_match('#(/-/.*)/OBJ#s', $path, $match);
    $result = $match[1];
    $path = str_replace($result, '', $path);
    $path = str_replace($label, '', $path);

    $obj = $fedora_item->get_datastream('OBJ');
    $file->filepath = $path;
    $file->filename = $obj->label;
    $file->filemime = $obj->MIMEType;
    $file->filesize = $obj->size;
    $file->description = $fedora_item->objectProfile->objLabel;
    $file->pid = $PID;
    $file->list = 1;
  }
  else {
    $file = NULL;
  }
  return $file;
}

function islandora_attachment_validate(&$form, &$form_state) {
  if (!empty($form_state['values']['islandora_files'])) {
    foreach ($form_state['values']['islandora_files'] as $file) {
      if (empty($file['description'])) {
        form_set_error('', t('All files must have a description.'));
      }
    }
  }
}

/**
 * Convert a fedora object into a file object so the form can display it like a file.
 *  @param $node
 *  The Node to get related PIDs.
 *  @return $files
 *  Returns an array of the converted fedora objects to files.
 */
function islandora_get_PIDs($node) {
  //Include fedora_item.inc
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');

  $pids = array();
  $files = array();
  $result = db_query('SELECT pid FROM {node_fedora_objects} WHERE nid = %d', $node->nid);

  while ($pid = db_fetch_object($result)) {
    array_push($pids, $pid->pid);
  }

  foreach ($pids as $pid) {
    $fedora_item = new Fedora_Item($pid);
    if ($fedora_item->exists()) {
      $tempfile = islandora_obj_to_file($pid);
      if (!empty($tempfile)) {
        array_push($files, $tempfile);
      }
    }
  }
  return $files;
}

function _islandora_upload_form($node) {
  global $user;

  $form = array(
    '#theme' => 'islandora_upload_form_new',
    '#cache' => TRUE,
  );

  if (!empty($node->islandora_files) && is_array($node->islandora_files)) {

    $form['islandora_files']['#theme'] = 'islandora_upload_form_current';
    $form['islandora_files']['#tree'] = TRUE;
    foreach ($node->islandora_files as $key => $file) {
      $file = (object)$file;

      $form['islandora_files'][$key]['description'] = array('#type' => 'textfield', '#default_value' => !empty($file->description) ? $file->description : $file->filename, '#maxlength' => 256, '#description' => $description );
      $form['islandora_files'][$key]['mimetype'] = array('#value' => $file->filemime);
      $form['islandora_files'][$key]['size'] = array('#value' => format_size($file->filesize));
      $form['islandora_files'][$key]['remove'] = array('#type' => 'checkbox', '#default_value' => !empty($file->remove));
      //$form['islandora_files'][$key]['list'] = array('#type' => 'checkbox',  '#default_value' => $file->list);
      $form['islandora_files'][$key]['weight'] = array('#type' => 'weight', '#delta' => count($node->islandora_files), '#default_value' => $file->weight);
      $form['islandora_files'][$key]['filename'] = array('#type' => 'value',  '#value' => $file->filename);
      $form['islandora_files'][$key]['filepath'] = array('#type' => 'value',  '#value' => $file->filepath);
      $form['islandora_files'][$key]['filemime'] = array('#type' => 'value',  '#value' => $file->filemime);
      $form['islandora_files'][$key]['filesize'] = array('#type' => 'value',  '#value' => $file->filesize);
      //$form['islandora_files'][$key]['fid'] = array('#type' => 'value',  '#value' => $file->fid);
      $form['islandora_files'][$key]['new'] = array('#type' => 'value', '#value' => FALSE);
    }
  }


  if (user_access('attach files')) {
    $limits = _islandora_upload_file_limits($user);
    $form['new']['#weight'] = 10;
    $form['new']['upload'] = array(
      '#type' => 'file',
      '#title' => t('Attach new file'),
      '#size' => 40,
      '#description' => ($limits['resolution'] ? t('Images are larger than %resolution will be resized. ', array('%resolution' => $limits['resolution'])) : '') . t('The maximum upload size is %filesize. Only files with the following extensions may be uploaded: %extensions. ', array('%extensions' => $limits['extensions'], '%filesize' => format_size($limits['file_size']))),
    );
    $form['new']['attach'] = array(
      '#type' => 'submit',
      '#value' => t('Attach'),
      '#name' => 'attach',
      '#ahah' => array(
        'path' => 'islandora_upload/js',
        'wrapper' => 'attach-wrapper',
        'progress' => array('type' => 'bar', 'message' => t('Please wait...')),
      ),
      '#submit' => array('node_form_submit_build_node'),
    );
  }

  return $form;
}


function islandora_upload_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'node_type_form' && isset($form['identity']['type'])) {
    $form['workflow']['upload'] = array(
      '#type' => 'radios',
      '#title' => t('Attachments'),
      '#default_value' => variable_get('upload_'. $form['#node_type']->type, 1),
      '#options' => array(t('Disabled'), t('Enabled')),
    );
  }

  if (isset($form['type']) && isset($form['#node'])) {
    $node = $form['#node'];
    if ($form['type']['#value'] .'_node_form' == $form_id && variable_get("upload_$node->type", TRUE)) {
      // Attachments fieldset
      $form['attachments'] = array(
        '#type' => 'fieldset',
        //'#access' => user_access('attach files'),
        '#title' => t('Islandora attachments'),
        '#collapsible' => TRUE,
        '#collapsed' => empty($node->islandora_files),
        '#description' => t('Changes made to the attachments are not permanent until you save this post. The first "listed" file will be included in RSS feeds.'),
        '#prefix' => '<div class="attachments">',
        '#suffix' => '</div>',
        '#weight' => 30,
      );
      $form['#validate'][] = 'islandora_attachment_validate';
      // Wrapper for fieldset contents (used by ahah.js).
      $form['attachments']['wrapper'] = array(
        '#prefix' => '<div id="attach-wrapper">',
        '#suffix' => '</div>',
      );

      // Make sure necessary directories for ialandora_upload.module exist and are
      // writable before displaying the attachment form.
      $path = file_directory_path();
      $temp = file_directory_temp();
      // Note: pass by reference
      if (!file_check_directory($path, FILE_CREATE_DIRECTORY) || !file_check_directory($temp, FILE_CREATE_DIRECTORY)) {
        $form['attachments']['#description'] =  t('File attachments are disabled. The file directories have not been properly configured.');
      }
      else {
        $form['attachments']['wrapper'] += _islandora_upload_form($node);
        $form['#attributes']['enctype'] = 'multipart/form-data';
      }
      $form['#submit'][] = 'islandora_upload_node_form_submit';
    }
  }
}

/**
 * Implementation of hook_nodeapi().
 */

function islandora_upload_nodeapi(&$node, $op, $teaser = NULL) {
  global $user;
  switch ($op) {

    case 'load':
      $output = '';
      if (variable_get("islandora_upload_$node->type", 1) == 1) {
        $output['islandora_files'] = islandora_upload_load($node);
        return $output;
      }
      break;

    case 'view':
        if (isset($node->islandora_files) && user_access('view attached files')) {
          // Add the attachments list to node body with a heavy
          // weight to ensure they're below other elements
          if (count($node->islandora_files)) {
            if (!$teaser && user_access('view attached files')) {
              $node->content['islandora_files'] = array(
                '#value' => theme('islandora_upload_attachments', $node->islandora_files),
                '#weight' => 50,
              );
            }
          }
        }
      break;

    case 'insert':
      if (user_access('upload files')) {
        islandora_upload_save($node, $user->uid);
      }
      if (count($node->islandora_files)) {
        $_REQUEST['destination'] = 'node/islandora_file_permissions/'. $node->nid;
      }
      break;

    case 'update':
      if (user_access('attach files')) {
        islandora_upload_save($node, $user->uid);
      }
      if (count($node->islandora_files)) {
        $_REQUEST['destination'] = 'node/islandora_file_permissions/'. $node->nid;
      }
      break;

    case 'delete':
      islandora_upload_delete($node);
      break;

    case 'search result':
      return isset($node->islandora_files) && is_array($node->islandora_files) ? format_plural(count($node->islandora_files), '1 attachment', '@count attachments') : NULL;

    case 'rss item':
      if (is_array($node->islandora_files)) {
        $files = array();
        foreach ($node->islandora_files as $file) {
          if ($file->list) {
            $files[] = $file;
          }
        }
        if (count($files) > 0) {
          // RSS only allows one enclosure per item
          $file = array_shift($files);
          return array(
            array(
              'key' => 'enclosure',
              'attributes' => array(
                'url' => file_create_url($file->filepath),
                'length' => $file->filesize,
                'type' => $file->filemime
              )
            )
          );
        }
      }
      return array();
  }
}

/**
 * Displays file attachments in table
 *
 * @ingroup themeable
 */
function theme_islandora_upload_attachments($files) {
  $header = array(t('Attachment'), t('Size'));
  $rows = array();
  foreach ($files as $file) {
    $file = (object)$file;
    if ($file->list && empty($file->remove)) {
      // $href = file_create_url($file->filepath);
      $href = $file->filepath;
      $text = $file->description ? $file->description : $file->filename;
      $rows[] = array(l($text, $href), format_size($file->filesize));
    }
  }
  if (count($rows)) {
    return theme('table', $header, $rows, array('id' => 'attachments'));
  }
}

/**
 * Used to save, update or delete files from a node during edit or insert.
 *
 * @params $node, $uid
 * The node and the current user id.
 */
function islandora_upload_save(&$node, $uid) {
  if (empty($node->islandora_files) || !is_array($node->islandora_files)) {
    return;
  }

  $new_pids = array();

  foreach ($node->islandora_files as $fid => $file) {
    // Convert file to object for compatibility
    $file = (object)$file;

    // Remove file. Process removals first since no further processing
    // will be required.
    if (!empty($file->remove)) {
     // call delete function which either purges or edits the pid
      if (!empty($file->pid)) {

      }

      // Remove it from the session in the case of new uploads,
      // that you want to disassociate before node submission.
      unset($node->islandora_files[$fid]);
      // Move on, so the removed file won't be added to new revisions.
      continue;
    }

    // Create a new revision, or associate a new file needed.
    if ($file->new) {

      // Params for ingest_new_item($pid = '', $state = 'A', $label = '', $owner = '')
      // IMPORTANT NOTE: THE OBJ AND PID LABEL SHOULD ALWAYS MATCH
      $fedora_item = Fedora_Item::ingest_new_item(Fedora_Item::get_next_PID_in_namespace("islandora"), 'A', $file->description);
      $fedora_item->add_datastream_from_file($file->filepath, "OBJ", $file->filename);
      $fedora_item->add_relationship("fedora:isMemberOfCollection", "islandora:sp_generic_collection");
      array_push($new_pids, $fedora_item->pid);
    }
    // Update existing revision.
    else {
      //db_query("UPDATE {attach_files} SET list = %d, description = '%s', weight = %d WHERE fid = %d AND vid = %d", $file->list, $file->description, $file->weight, $file->fid, $node->vid);
    }
  }

  foreach ($new_pids as $pid) {
    db_query("INSERT INTO {node_fedora_objects} (nid, pid, ownerid) VALUES (%d, '%s', %d)", $node->nid, $pid, $uid);
  }
}

/**
 *  Delete File records from fedora repo when node is deleted.
 *  TODO
 */
function islandora_upload_delete($node) {

}

/**
 *  Chooses purge if user has purge rights otherwise calls object delete.
 *  TODO
 */
function islandora_upload_purge_or_delete($pid, $uid) {

}

/**
 *  Load the fedora files saved to a node on edit and view.
 *  @param $node
 *  The current node.
 *  @results
 *  Files array containing all fedora objects saved to node.
 */
function islandora_upload_load($node) {
  $files = array();

  if ($node->vid)  {
    $files = islandora_get_PIDs($node);
  }
  return $files;
}

/**
 * When a file is uploaded this function will be called
 * to determine the MIME Type
 *
 * @param $file
 *  A file that is uploaded by the user
 *
 */

function islandora_check_mime($file) {

  if (!empty($file)) {
  // Grabs the default list of extensions currently defined
  // in islandora_upload.admin.inc
  $extensions = variable_get('upload_extensions_default', 'jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp');


  $errors = array();

    if (!empty($extensions)) {
      $regex = '/\.('. ereg_replace(' +', '|', preg_quote($extensions)) .')$/i';
      $matches = array();
      if (preg_match($regex, $file->filename, $matches)) {
        $extension = $matches[1];
        // If the extension validates, check that the mimetype matches.
        if (module_exists('mimedetect')) {
          $type = mimedetect_mime($file);
          if ($type != $file->filemime) {
            $errors[] = t('The file contents (@type) do not match its extension (@extension).', array('@type' => $type, '@extension' => $extension));
          }
        }
      }
      else {
        $errors[] = t('Only files with the following extensions are allowed: %files-allowed.', array('%files-allowed' => $extensions));
      }
    }

    $mime = implode($errors);

    return $mime;
  }

}

/**
 * Menu-callback for JavaScript-based uploads.
 */
function islandora_upload_js() {
  $cached_form_state = array();
  $files = array();

  // Load the form from the Form API cache.
  if (!($cached_form = form_get_cache($_POST['form_build_id'], $cached_form_state)) || !isset($cached_form['#node']) || !isset($cached_form['attachments'])) {
    form_set_error('form_token', t('Validation error, please try again. If this error persists, please contact the site administrator.'));
    $output = theme('status_messages');
    print drupal_to_js(array('status' => TRUE, 'data' => $output));
    exit();
  }

  $form_state = array('values' => $_POST);

  // Handle new uploads, and merge tmp files into node-files.
  islandora_upload_node_form_submit($cached_form, $form_state);

  if (!empty($form_state['values']['islandora_files'])) {
    foreach ($form_state['values']['islandora_files'] as $fid => $file) {
      if (isset($cached_form['#node']->islandora_files[$fid])) {
        $files[$fid] = $cached_form['#node']->islandora_files[$fid];
      }
    }
  }

  $node = $cached_form['#node'];

  $node->islandora_files = $files;
  $form = _islandora_upload_form($node);

  unset($cached_form['attachments']['wrapper']['new']);
  $cached_form['attachments']['wrapper'] = array_merge($cached_form['attachments']['wrapper'], $form);

  $cached_form['attachments']['#collapsed'] = FALSE;

  form_set_cache($_POST['form_build_id'], $cached_form, $cached_form_state);

  foreach ($files as $fid => $file) {
    if (is_numeric($fid)) {
      $form['islandora_files'][$fid]['description']['#default_value'] = $form_state['values']['islandora_files'][$fid]['description'];
      $form['islandora_files'][$fid]['list']['#default_value'] = !empty($form_state['values']['islandora_files'][$fid]['list']);
      $form['islandora_files'][$fid]['remove']['#default_value'] = !empty($form_state['values']['islandora_files'][$fid]['remove']);
      $form['islandora_files'][$fid]['weight']['#default_value'] = $form_state['values']['islandora_files'][$fid]['weight'];
    }
  }

  // Render the form for output.
  $form += array(
    '#post' => $_POST,
    '#programmed' => FALSE,
    '#tree' => FALSE,
    '#parents' => array(),
  );

  $empty_form_state = array();
  $data = &$form;
  $data['__drupal_alter_by_ref'] = array(&$empty_form_state);
  drupal_alter('form', $data, 'islandora_upload_js');

  $form_state = array('submitted' => FALSE);
  $form = form_builder('islandora_upload_js', $form, $form_state);
  $output = theme('status_messages') . drupal_render($form);

  // We send the updated file attachments form.
  // Don't call drupal_json(). ahah.js uses an iframe and
  // the header output by drupal_json() causes problems in some browsers.
  //$form = _islandora_upload_form($node);
  //$output = theme('status_messages') . drupal_render($form);
  print drupal_to_js(array('status' => TRUE, 'data' => $output));
  exit;
}

/**
 * When a Drupal Node is deleted this function will delete
 * all associated Fedora Objects Datasteams.
 *
 * @param $node
 *   A node object.
 * @param $uid
 *   The current User ID. (This is the user deleting the node)
 *
 */

function islandora_upload_delete_fedora_object_datastreams($node, $uid) {

  //Grab all pid attached to the drupal node
  $sql = "SELECT pid FROM {node_fedora_objects} WHERE nid = '" . $node->nid . "'";
  $results = db_query($sql);

  while ($PID = db_result($results)) { // Get the next result, which will/must always be a single field
    $fedora_item = new Fedora_Item($PID);
    if  ($fedora_item->exists())  {
      $dsid_array = $fedora_item->get_datastreams_list_as_array();
      foreach ($dsid_array as $dsid) {
        $state = 'D'; //Set the datastream to deleted
        $log_message = "Node {NID:" . $node->nid . "} created by {UID:" . $node->uid . "} which is associate with this object has been deleted by user {" . $uid . "}.";
        $fedora_item->set_datastream_state($dsid, $state, $log_message);
      }
    }
  }
  db_query("DELETE FROM {node_fedora_objects} where nid = '" . $node->nid . "'");
}

/**
 * When a Drupal Node is deleted this function will purge
 * all associated Fedora Objects
 *
 * @param $node
 *   A node object.
 * @param $uid
 *   The current User ID. (This is the user deleting the node)
 *
 */

function islandora_upload_purge_fedora_objects($node, $uid) {

  //Grab all pid attached to the drupal node
  $sql = "SELECT pid FROM {node_fedora_objects} WHERE nid = '" . $node->nid . "'";
  $results = db_query($sql);

  while ($PID = db_result($results)) { // Get the next result, which will/must always be a single field
    $fedora_item = new Fedora_Item($PID);
    if  ($fedora_item->exists())  {
      $log_message = "Node {NID:" . $node->nid . "} created by {UID:" . $node->uid . "} which is associate with this object has been purged by user {" . $uid . "}.";
      $fedora_item->purge($log_message, TRUE); //remove the fedora object
    }
  }
  db_query("DELETE FROM {node_fedora_objects} where nid = '" . $node->nid . "'");
}

/**
 * When a Drupal Node is deleted this function will set the fedora object state
 * of all associated Fedora Objects to D (Deleted).
 *
 * @param $node
 *   A node object.
 * @param $uid
 *   The current User ID. (This is the user deleting the node)
 *
 */

function islandora_upload_delete_fedora_objects($node, $uid) {

  //Grab all pid attached to the drupal node
  $sql = "SELECT pid FROM {node_fedora_objects} WHERE nid = '" . $node->nid . "'";
  $results = db_query($sql);

  while ($PID = db_result($results)) { // Get the next result, which will/must always be a single field
    $fedora_item = new Fedora_Item($PID);
    if  ($fedora_item->exists())  {
      $state = "D";
      $label = ""; // needs to be filled in with objects label.
      $ownerId = $node->uid; //The object owner is the node owner.
      $log_message = "Node {NID:" . $node->nid . "} created by {UID:" . $node->uid . "} which is associate with this object has been deleted by user {" . $uid . "}.";
      $fedora_item->modify_object($label, $state, $ownerId, $logMessage, TRUE);
    }
  }
  db_query("DELETE FROM {node_fedora_objects} WHERE nid = '" . $node->nid . "'");
}

/**
 * Used to get the node creator's UID.
 *
 * @param $pid
 *   The pid of the file attached to a node.
 * @return $result
 *   The Private User Name (owner of the node/file) or false
 *
 */

function get_file_private_uid($pid) {

  //Grab privateUID of a file using the PID
  $sql = "SELECT privateUID FROM {islandora_attachment_permissions} WHERE pid = '" . $pid . "'";
  $results = db_query($sql);
  $UID = db_result($results);
  if ($UID == "" || $UID == NULL) {
    $result = FALSE; //return false if file was not private
  }
  else {
    $result = $UID; //return owner UID
  }
  return $result;
}

/**
 * Used to get user ID's that are set as able to access a given fill.  Uses
 * PID to look up ID of {islandora_attachment_permissions} and then uses the ID
 * to grab any set group ids from {islandora_attachment_permission_users}
 *
 * @param $pid
 *   The pid of the file attached to a node.
 * @return $result
 *   An array of User Names(owner of the node/file) or false
 *
 */
function get_file_accessable_users($pid) {
  $result = array();
  //Grab iapid (islandora attachment permission ID) of a file using the PID to look up
  $sql = "SELECT iapid FROM {islandora_attachment_permissions} WHERE pid = '" . $pid . "'";
  $results = db_query($sql);
  $iapid = db_result($results);

  //ubid is the User Binding ID
  //Find all groups associate with islandora attachment permission ID
  $sql = "SELECT uid FROM {islandora_attachment_permission_users} WHERE ubid = '" . $iapid . "'";
  $results = db_query($sql);

  while ($UID = db_result($results)) { // Get the next result, which will/must always be a single field
    $sql2 = "SELECT name FROM {users} WHERE uid = '" . $UID . "'";
    $user_result = db_query($sql2);
    $user_name = db_result($user_result);
    $result[] = $user_name;
  }

  if (empty($result)) {
    $result[] = FALSE;
  }
  return $result;
}

/**
 * Used to get role ID's that are set as able to access a given file.  Uses
 * PID to look up ID of {islandora_attachment_permissions} and then uses the ID
 * to grab any set role ids from {islandora_attachment_permission_roles}
 *
 * @param $pid
 *   The pid of the file attached to a node.
 * @return $result
 *   An array of allowed role Names.
 *
 */

function get_file_accessable_roles($pid) {
  $result = array();
  //Grab iapid (islandora attachment permission ID) of a file using the PID to look up
  $sql = "SELECT iapid FROM {islandora_attachment_permissions} WHERE pid = '" . $pid . "'";
  $results = db_query($sql);
  $iapid = db_result($results);

  //rbid is the Role Binding ID
  //Find all roles associate with islandora attachment permission ID
  $sql = "SELECT rid FROM {islandora_attachment_permission_roles} WHERE rbid = '" . $iapid . "'";
  $results = db_query($sql);

  while ($RID = db_result($results)) { // Get the next result, which will/must always be a single field
    $sql2 = "SELECT name FROM {role} WHERE rid = '" . $RID . "'";
    $role_result = db_query($sql2);
    $role_name = db_result($role_result);
    $result[] = $role_name;
  }

  if (empty($result)) {
    $result[] = FALSE;
  }
  return $result;
}

function islandora_upload_file_permission_form_submit($form, &$form_state) {
  //check files that are set and if not set set to public?

  // url example ?q=node/islandora_file_permissions/22
  // arg(0) = node, arg(1) = islandora_file_permissions, arg(2) = 22
  $node_id = "";
  if (arg(1) == 'islandora_file_permissions' && is_numeric(arg(2))) {
    $node_id = arg(2); // Grab NID from URL
  }
  $form_state['redirect'] = 'node/'. $node_id; // Redirects the user.
}

function islandora_upload_permissions_form() {

  // This form calls the form builder function via the
  // drupal_get_form() function which takes the name of this form builder
  // function as an argument. It returns the results to display the form.
  return drupal_get_form('islandora_upload_file_permission_form');

}

/**
 * This function is called the "form builder". It builds the form.
 * Notice, it takes one argument, the $form_state
 */
function islandora_upload_file_permission_form($form_state) {
  global $user;
  // Get Node ID from url
  // url example ?q=node/islandora_file_permissions/22
  // arg(0) = node, arg(1) = islandora_file_permissions, arg(2) = 22
  if (arg(1) == 'islandora_file_permissions' && is_numeric(arg(2))) {
    $node_id = check_plain(arg(2)); // Grab NID from URL
  }
  //get node owner
  $results_node_owner = db_query("SELECT uid FROM {node} WHERE nid = %d", $node_id);
  $node_ownerid = db_result($results_node_owner);

  // Load fedora_item.inc from the fedora_repository module in the api folder.
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');

  if ($_POST['op'] == "Save Permissions" && $_POST['files'] != '0') {
    //if($_POST['files'] == "all");
    //set for all files
    //set a success message so user knows their permission choice was saved.
    print_r($_POST);
    $permission_radio =  check_plain($_POST['permission_radios']);
    $remove_path = base_path() . "?q=filepermissions/get/";
    $object_pid = str_replace($remove_path, "", check_plain($_POST['files'])); //string replace to get the file pid
    $fedora_item_temp = new Fedora_Item($object_pid);
    if ($fedora_item_temp->exists()) {
        $results_check = db_query("SELECT iapid, public_permission, private_permission FROM {islandora_attachment_permissions} WHERE pid = '%s'", $object_pid);
        if ($row = db_fetch_object($results_check)) {
          $iapid = $row->iapid;
          $exists = TRUE;
        }
        else {
          $iapid = "";
          $exists = FALSE;
        }
      $label = $fedora_item_temp->objectProfile->objLabel;
      $message = "The selected access permission has been applied to " . $label . ".";
      drupal_set_message(check_plain($message), 'status');
      //  Master Switch to control how to save permissions based on radio input
      // 0 - public, 1 - private, 2 - Role Based, 3 - User Based
      // Admin role access is granted by Xacml by default
      // Have to always add current user + node owner
        switch ($permission_radio)  {
          case '0':
            if ($exists) {
              //delete queries to clear out roles and users
              db_query("DELETE FROM {islandora_attachment_permission_users} WHERE ubid = '%d' ", $iapid);
              db_query("DELETE FROM {islandora_attachment_permission_roles} WHERE rbid = '%d' ", $iapid);
              //update query
              db_query("UPDATE {islandora_attachment_permissions} SET public_permission = 1, private_permission = 0 WHERE pid = '%s' ", $object_pid);
              //Remove other XACML
              islandora_upload_purge_xacml_policy($object_pid, $user->uid);
            }
            else {
              //Set permissions to public - public objects have no XACML
              //insert query
              db_query("INSERT INTO {islandora_attachment_permissions} (public_permission, private_permission, pid) VALUES (1, 0, '%s')", $object_pid);
            }
            break;

          case '1':
            if ($exists) {
              //delete queries to clear out roles and users
              db_query("DELETE FROM {islandora_attachment_permission_users} WHERE ubid = '%d' ", $iapid);
              db_query("DELETE FROM {islandora_attachment_permission_roles} WHERE rbid = '%d' ", $iapid);
              //update query
              db_query("UPDATE {islandora_attachment_permissions} SET public_permission = 0, private_permission = 1 WHERE pid = '%s' ", $object_pid);

            }
            else {
              //insert query
              db_query("INSERT INTO {islandora_attachment_permissions} (public_permission, private_permission, pid) VALUES (0, 1, '%s')", $object_pid);
              $result_iapid = db_query("SELECT iapid FROM {islandora_attachment_permissions} WHERE pid = '%s'", $object_pid);
              $iapid = db_result($result_iapid);
            }
            islandora_upload_create_xacml_policy_private($object_pid, $user->uid, $node_ownerid);
            break;

          case '2':
            if  ($exists) {
              //delete queries to clear out roles and users
              db_query("DELETE FROM {islandora_attachment_permission_users} WHERE ubid = '%d' ", $iapid);
              db_query("DELETE FROM {islandora_attachment_permission_roles} WHERE rbid = '%d' ", $iapid);
              //update query
              db_query("UPDATE {islandora_attachment_permissions} SET public_permission = 0, private_permission = 0 WHERE pid = '%s' ", $object_pid);
            }
            else {
              //insert query
              db_query("INSERT INTO {islandora_attachment_permissions} (public_permission, private_permission, pid) VALUES (0, 0, '%s')", $object_pid);
              //select query to get new ID
              $result_iapid = db_query("SELECT iapid FROM {islandora_attachment_permissions} WHERE pid = '%s'", $object_pid);
              $iapid = db_result($result_iapid);
            }
            //insert checked roles
            if (isset($_POST['roles'])) {
              foreach ($_POST['roles'] as $value) {
                //insert query
                db_query("INSERT INTO {islandora_attachment_permission_roles} (rbid, rid) VALUES ('%d','%d')", $iapid,  check_plain($value));
              }
            }
            islandora_upload_create_xacml_policy_roles($object_pid, $user->uid, $node_ownerid);
            break;

          case '3':
            if ($exists) {
              //delete queries to clear out roles and users
              db_query("DELETE FROM {islandora_attachment_permission_users} WHERE ubid = '%d' ", $iapid);
              db_query("DELETE FROM {islandora_attachment_permission_roles} WHERE rbid = '%d' ", $iapid);
              //update query
              db_query("UPDATE {islandora_attachment_permissions} SET public_permission = 0, private_permission = 0 WHERE pid = '%s' ", $object_pid);
            }
            else {
              //insert query
              db_query("INSERT INTO {islandora_attachment_permissions} (public_permission, private_permission, pid) VALUES (0, 0, '%s')", $object_pid);
              //select query to get new ID
              $result_iapid = db_query("SELECT iapid FROM {islandora_attachment_permissions} WHERE pid = '%s'", $object_pid);
              $iapid = db_result($result_iapid);
            }
            //insert checked users
            if (isset($_POST['users'])) {
              foreach ($_POST['users'] as $value) {
                //insert query
                db_query("INSERT INTO {islandora_attachment_permission_users} (ubid, uid) VALUES ('%d','%d')", $iapid,  check_plain($value));
              }
            }
            islandora_upload_create_xacml_policy_users($object_pid, $user->uid, $node_ownerid);
            break;
          }
    }
    //unset so file is unselected - otherwise the Ajax will not load until you browse off that object and it
    //will not pull the users and roles.
    unset($_POST['files']);
  }
  drupal_add_js(drupal_get_path('module', 'islandora_upload') . '/permission_selectbox.js');
  drupal_add_css(drupal_get_path('module', 'islandora_upload') .'/islandora_upload.css');

  $results = db_query("SELECT pid FROM {node_fedora_objects} WHERE nid = %d", $node_id);
  $file_array = array();
  $file_array['0'] = ""; //white space for first record of the drop down.
  //$file_array[base_path() . "?q=filepermissions/get/all"] = "Set All"; //white space for first record of the drop down.
  while ($row = db_fetch_object($results)) {
    //get fedora label for pid
    $fedora_item = new Fedora_Item($row->pid);
    $label = $fedora_item->objectProfile->objLabel;
    $file_array[base_path() . "?q=filepermissions/get/" . $row->pid] = $label;
    $perm_check = db_query("SELECT iapid FROM {islandora_attachment_permissions} WHERE pid = '%s'", $row->pid);
    if (!db_fetch_object($perm_check)) {
      //Set permissions to public - public objects have no XACML
      db_query("INSERT INTO {islandora_attachment_permissions} (public_permission, private_permission, pid) VALUES (1, 0, '%s')", $row->pid);
    }
  }
  $form['description'] = array(
    '#id' => 'islandora_files_description',
    '#type' => 'item',
    '#description' => t('Select a file to set file access permissions, if you don\'t care about access permission just you can skip this process by just clicking "Finished" and all files will be assigned public access. Important Note: Be sure to click the "Save Permissions" button before changing to a new file and set all files before this way before clicking Finished or they will default to public.'),
  );
  // Select Box with all the FID and file descriptions(labels)
  $form['files'] = array(
    '#id' => 'islandora_files',
    '#type' => 'select',
    '#title' => t('Select File'),
    '#options' => $file_array,
  );
  // add in style="display: none;" to prefix div for method two of the UI
  $form['permissions'] = array(
    '#type' => 'fieldset',
    //'#access' => user_access('attach files'),
    '#title' => t('File Permissions'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#description' => t('When finished setting the files access permissions click "Save Permissions" before selection another file or clicking "Finished". Please note that a file can only have one of the following permission options: Public Access, Private Access, Roles Based Access, or User Based Access.  If role based you must select off all roles that you wish to grant access to, and if user based you must check all users you wish to grant file access to.'),
    '#prefix' => '<div class="permission-container">',
    '#suffix' => '</div>'
  );
  $form['permissions']['permission_radios'] = array(
    '#id' => 'permission_options',
    '#type' => 'radios',
    '#title' => t('Permission Category'),
    '#default_value' => 0,
    '#options' => array(t('Public'), t('Private'), t('Roles'), t('Users')),
    '#prefix' => '<span class="permission_radio_span">',
    '#suffix' => '</span>',
  );
  // Need hidden to get the permission_results div to show which is used by ajax.
  $form['permissions']['results_user'] = array(
   '#type' => 'hidden',
   '#value' => '',
   '#prefix' => '<div id="permission_result_users" style="display: none;">',
   '#suffix' => '</div>',
  );
  // Need hidden to get the permission_results div to show which is used by ajax.
  $form['permissions']['results_role'] = array(
    '#type' => 'hidden',
    '#value' => '',
    '#prefix' => '<div id="permission_result_roles" style="display: none;">',
    '#suffix' => '</div>',
  );
  $form['permissions']['save'] = array(
    '#id' => 'my_button',
    '#type' => 'button',
    '#value' => 'Save Permissions',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Finished',
  );
  return $form;
}

function islandora_upload_get_by_file_id($fedora_pid) {
  //string pad variables for better spacings
  $items = array();
  $checked_role_array = array();
  $checked_user_array = array();
  $checked_role_array["prechecked-islandora-upload"] = "Array Exists";
  $checked_user_array["prechecked-islandora-upload"] = "Array Exists";


  //get owner id of the file
  $ownerID = "";
  $radio_option = 0;
  $node_ownerid = "";

  $results = db_query("SELECT ownerid, nid FROM {node_fedora_objects} WHERE pid = '%s'", $fedora_pid);
  if ($row_setup = db_fetch_object($results)) {
    $ownerID = $row_setup->ownerid;
    $nid = $row_setup->nid;
    $result_node_owner = db_query("SELECT uid FROM {node} WHERE nid = %d", $nid);
    if ($row_node_owner = db_fetch_object($result_node_owner)) {
      $node_ownerid = $row_node_owner->uid;
    }
  }

  //get binding id and then get all user / roles if they exists
  $results_check = db_query("SELECT iapid, public_permission, private_permission FROM {islandora_attachment_permissions} WHERE pid = '%s'", $fedora_pid);
  if ($row = db_fetch_object($results_check)) {

    $binding_id = $row->iapid;
    if ($row->public_permission) {
      $radio_option = 0;

    }
    elseif ($row->private_permission) {
      $radio_option = 1;
    }
    else {

      //grab all roles saved
      $results_roles = db_query("SELECT rid FROM {islandora_attachment_permission_roles} WHERE rbid = %d", $binding_id);
      while ($row_roles = db_fetch_object($results_roles)) {
        $checked_role_array[$row_roles->rid] = $row_roles->rid;
      }
      //if roles were pulled set option to 2
      if (count($checked_role_array) > 1) {
        $radio_option = 2;
      }
      else {
        //otherwise try to get grab all users saved
        $results_users = db_query("SELECT uid FROM {islandora_attachment_permission_users} WHERE ubid = %d", $binding_id);
        while ($row_users = db_fetch_object($results_users)) {
          $checked_user_array[$row_users->uid] = $row_users->uid;
        }

        //if users were pulled set option to 3
        if (count($checked_user_array) > 1) {
          $radio_option = 3;
        }
        else {
          $radio_option = 0;  //Should ever get called but it's a fail safe
        }
      }
    }
  }
  //get user count
  $count_users = 0;
  if ($node_ownerid == $ownerID) {
    $results = db_query("SELECT count(uid) FROM {users} where uid NOT IN (0, %d)", $ownerID);
  }
  else {
    $results = db_query("SELECT count(uid) FROM {users} where uid NOT IN (0, %d, %d)", $ownerID, $node_ownerid);
  }
  if ($count_rows = db_result($results)) {
    $count_users = $count_rows;
  }

  //get role count
  $count_roles = 0;
  $results = db_query("SELECT rid, name FROM {role}");
  if ($count_rows = db_result($results)) {
    $count_roles = $count_rows;
  }

  // Pass the Radio button to be checked off the default is Public.
  // edit-permission-radios-0 is Public with a value 0.
  // edit-permission-radios-1 is Private with a value 1.
  // edit-permission-radios-2 is Roles with a value 2.
  // edit-permission-radios-3 is Users with a value 3.
  switch ($radio_option) {
    case 0:
      $radio_button = "edit-permission-radios-0";
      break;
    case 1:
      $radio_button = "edit-permission-radios-1";
      break;
    case 2:
      $radio_button = "edit-permission-radios-2";
      break;
    case 3:
      $radio_button = "edit-permission-radios-3";
      break;

  }
  $items[] = array(
    'radio_checked' => $radio_option,
    'number_of_users' => $count_users,
    'number_of_roles' => $count_roles,
    'owner_id' => $ownerID,
    'debug' => $radio_button);

  if ($node_ownerid == $ownerID) {
    $results = db_query("SELECT uid, name FROM {users} where uid NOT IN (0, %d)", $ownerID);
  }
  else {
    $results = db_query("SELECT uid, name FROM {users} where uid NOT IN (0, %d, %d)", $ownerID, $node_ownerid);
  }
  while ($row = db_fetch_object($results)) {
    //if current user is one of the saved users send checked = TRUE so the JS checkes the box on load
    if (array_key_exists($row->uid, $checked_user_array) ) {
      $checked = TRUE;
    }
    else {
      $checked = FALSE;
    }
    $items[] = array(
      'data' => $row->name,
      'id_value' => $row->uid,
      'checked' => $checked,
      'debug' => "debug message user");
  }

  $results = db_query("SELECT rid, name FROM {role}");
  while ($row = db_fetch_object($results)) {

    //if role is one of the saved roles send checked = TRUE so the JS checkes the box on load
    if (array_key_exists($row->rid, $checked_role_array) ) {
      $checked = TRUE;
    }
    else {
      $checked = FALSE;
    }

    $items[] = array(
      'data' => $row->name,
      'id_value' => $row->rid,
      'checked' => $checked,
      'owner' =>  FALSE,
      'debug' => "debug message role");
  }

// create a JSON object. The object will contain a property named “products” that will be set with the $items variable.
  echo json_encode($items);
  exit;
}

/**
 * Generates and Attaches XACML Policy to specificied PID using Owner and Node Owner.
 *
 *  @param pid
 *  Object PID
 *  @param uid
 *  Current User's Id - get name and set to management
 *  @param node_ownerid
 *  Node Owner's id - get name and set to management
 *
 */
function islandora_upload_create_xacml_policy_private($pid, $uid, $node_ownerid) {
  $sql = "SELECT name FROM {users} WHERE uid = '" . $uid . "'";
  $user_result = db_query($sql);
  $user_name = db_result($user_result);
  //Only need node owner if it is a different user
  if ($uid != $node_ownerid) {
    $sql2 = "SELECT name FROM {users} WHERE uid = '" . $node_ownerid . "'";
    $owner_result = db_query($sql2);
    $owner_name = db_result($owner_result);
  }
  else {
    $owner_name = "";
  }
  //Generate XACML

  //Attach XACML
  $fedora_item = new Fedora_Item($pid);
  if ($fedora_item->exists()) {
    $datastream_array = $fedora_item->get_datastreams_list_as_array();
    if (array_key_exists('POLICY', $datastream_array)) {
      //$fedora_item->modify_datastream_by_value($xml, 'POLICY', 'Xacml Policy Stream', 'text/xml');
    }
    else {
      //$fedora_item->add_datastream_from_string($xml, 'POLICY', 'Xacml Policy Stream', 'text/xml', 'X');
    }
  }
}

/**
 * Generates and Attaches XACML Policy to specificied PID using Users.
 *
 *  @param pid
 *  Object PID
 *  @param uid
 *  Current User's Id - get name and set to management
 *  @param node_ownerid
 *  Node Owner's id - get name and set to management
 *
 */
function islandora_upload_create_xacml_policy_users($pid, $uid, $node_ownerid) {
  // Load fedora_item.inc from the fedora_repository module in the api folder.
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');

  $sql = "SELECT name FROM {users} WHERE uid = '" . $uid . "'";
  $user_result = db_query($sql);
  $user_name = db_result($user_result);
  //Only need node owner if it is a different user
  if ($uid != $node_ownerid) {
    $sql2 = "SELECT name FROM {users} WHERE uid = '" . $node_ownerid . "'";
    $owner_result = db_query($sql2);
    $owner_name = db_result($owner_result);
  }
  else {
    $owner_name = "";
  }
  $fedora_item = new Fedora_Item($pid);
  if ($fedora_item->exists()) {
    //Get Users - returns an array of user names or null if the table is empty
    $users = get_file_accessable_users($pid);
    //Generate XACML

    //Attach XACML
    $datastream_array = $fedora_item->get_datastreams_list_as_array();
    if (array_key_exists('POLICY', $datastream_array)) {
      //$fedora_item->modify_datastream_by_value($xml, 'POLICY', 'Xacml Policy Stream', 'text/xml');
    }
    else {
      //$fedora_item->add_datastream_from_string($xml, 'POLICY', 'Xacml Policy Stream', 'text/xml', 'X');
    }
  }
}

/**
 * Generates and Attaches XACML Policy to specificied PID using Roles.
 *
 *  @param pid
 *  Object PID
 *  @param uid
 *  Current User's Id - get name and set to management
 *  @param node_ownerid
 *  Node Owner's id - get name and set to management
 *
 */
function islandora_upload_create_xacml_policy_roles($pid, $uid, $node_ownerid) {
  // Load fedora_item.inc from the fedora_repository module in the api folder.
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');

  $sql = "SELECT name FROM {users} WHERE uid = '" . $uid . "'";
  $user_result = db_query($sql);
  $user_name = db_result($user_result);
  //Only need node owner if it is a different user
  if ($uid != $node_ownerid) {
    $sql2 = "SELECT name FROM {users} WHERE uid = '" . $node_ownerid . "'";
    $owner_result = db_query($sql2);
    $owner_name = db_result($owner_result);
  }
  else {
    $owner_name = "";
  }
  $fedora_item = new Fedora_Item($pid);
  if ($fedora_item->exists()) {
    //Get Roles - returns an array of role names or null if the table is empty
    $roles = get_file_accessable_roles($pid);
    //Generate XACML

    //Attach XACML
    $datastream_array = $fedora_item->get_datastreams_list_as_array();
    if (array_key_exists('POLICY', $datastream_array)) {
      //$fedora_item->modify_datastream_by_value($xml, 'POLICY', 'Xacml Policy Stream', 'text/xml');
    }
    else {
      //$fedora_item->add_datastream_from_string($xml, 'POLICY', 'Xacml Policy Stream', 'text/xml', 'X');
    }
  }
}

/**
 * Generates and Attaches XACML Policy to specificied PID using.
 *
 *  @param pid
 *  Object PID
 *
 */
function islandora_upload_purge_xacml_policy($pid, $uid) {
  // Load fedora_item.inc from the fedora_repository module in the api folder.
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $fedora_item = new Fedora_Item($pid);
  if ($fedora_item->exists()) {
    $datastream_array = $fedora_item->get_datastreams_list_as_array();
    if (array_key_exists('POLICY', $datastream_array)) {
      $log_message = "Object has been set to public by user {" . $uid . "}.";
      $fedora_item->purge_datastream('POLICY', NULL, NULL, $log_message);
    }
  }

}